### ISSUE TITLE
Ignore build-related files

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#139]
# Clarification and motivation

At the moment, we're using the `ignored` option for mainly 2 purposes:

1. to ignore all files in the `.git` folder (`.git/**/*`)
2. to ignore all build-related temporary files (the default config ignores `.stack-work/**/*`)

Regarding point (2): 
* It would be useful to ignore not only `.stack-work` but also `dist-newstyle`.
* `.stack-work` is specific to Haskell projects. Other languages/build tools will have their own directories they want to ignore (e.g. `node_modules`).
* We can't possibly list all build-related directories related to all languages/tools. Which means that, with this approach, there'll always be a bias towards the languages/tools **we** use ourselves.

~A more robust alternative might be to introduce a new option, `useGitIgnore`, which ignores all files ignored by `.gitignore`.~
A more robust alternative might be to ignore all files implicitly ignored by git.

Internally, we could use the ~[`git check-ignore <filename>`](https://git-scm.com/docs/git-check-ignore)~ [`git ls-files`](https://git-scm.com/docs/git-ls-files) command to implement this.

~This option's default value should be `true`.~

As part of this issue, let's also try and refactor `gatherRepoInfo` so that it uses `git ls-files` instead of `Tree.readDirectoryWithL`.

# Acceptance criteria

* ~By default,~ we automatically ignore all files ignored by git
* ~The user can optionally disable this behaviour.~
* ~The option's description~ The readme should mention this requires having git >= 2.18.0 in the PATH.

**Comment by dcastro** [comment]
A few more things:
* Instead of running `git check-ignore` for every file, it might be better to run [`git ls-files`](https://git-scm.com/docs/git-ls-files) once at the start and keep that in memory.
* Maybe this shouldn't be an option at all. I'm starting to think this should be just built-in hardcoded behavior. If a file exists on disk but is not being tracked by git, then surely linking to it will result in a broken link.
* If this is not a git repository (see below for an example of git's error message), then it's possible this is mercurial/svn/something-else repository. We should carry on and skip this check.
  * The same logic applies if `git` is not installed.
   ```
   $ cd ~ && git ls-files
   fatal: not a git repository (or any of the parent directories): .git
   ```
* What if `git` is not installed? This is trickier... Is there a conceivable scenario where `xrefcheck` would be asked to check a git repo in an environment where `git` is not installed? I can't think of any. Even if a CI+nix environment, if this is a git repository, surely had to clone the repo first, and you need `git` for that.
  * I'm tempted to say we should also carry on and skip this check in this scenario, but maybe print a warning to stdout as well.

**Comment by Martoon-00** [comment]
That's a good suggestion to consider ignored what `git ` thinks should be ignored.

I once was thinking about doing this in 2 stages:
* Make the user specify not glob-patterns but `.gitignored`-like patterns in config. They are more concise (e.g. `**.hs` instead of `**/*.hs`), and eventually specifying the same exclusions twice but in different formats in `.gitignore` and `.xrefcheck.yaml` seemed annoying.
* Automatically include `.gitignore` into the exclusions.

But now I see the problem with this: `.gitignore` is not the only source of exclusions honored by `git`, rather there can be a file with custom name, and there is also a system-global file with exclusions, so it might be tricky to support properly.

---

On your proposal with `git ls-files`, I'm now also thinking that this just had to be the initial behaviour, instead of collecting files manually. It is easier and functionally much more appropriate.

We really support only git repositories, since we have a `mode` option that affects how anchors should be rendered.

On whether can `git` be not installed... Looks like if the user has any given repository, he likely cloned it or initialized locally with `git`. In case the user got an archive with this repository (circumventing the use of `git` tool) likely means that he is not planning to work a lot with the repo, I would also ignore this possibility.

**Comment by dcastro** [comment]
> But now I see the problem with this: .gitignore is not the only source of exclusions honored by git, rather there can be a file with custom name, and there is also a system-global file with exclusions, so it might be tricky to support properly.

Also, if you add a file to the repo, and _then_ add it to `.gitignore`, git will continue tracking it :P just another level of complexity :sweat_smile:  `git check-ignore` and `git ls-files` that all of this into account.

--- 

> We really support only git repositories, since we have a mode option that affects how anchors should be rendered.

Oh right, great point!

So, if the xrefcheck only works on git repos by design, then I think it makes sense to require `git` to be installed.

In that case, xrefcheck should fail and exit if (1) the root dir is not inside a git repo or (2) `git` is not installed.


----

> On your proposal with `git ls-files`, I'm now also thinking that this just had to be the initial behaviour, instead of collecting files manually. It is easier and functionally much more appropriate.

Agreed. As part of this issue, let's also try and refactor `gatherRepoInfo` so that it uses `git ls-files` instead of `Tree.readDirectoryWithL`.

**Comment by Martoon-00** [comment]
> Also, if you add a file to the repo, and then add it to .gitignore, git will continue tracking it :P just another level of complexity sweat_smile git check-ignore and git ls-files that all of this into account.

Oh reeally, that would a bug-by-design :sweat_smile: 

So yes, `git ls-files` is definitely the best option.
