### ISSUE TITLE
Setup CI to run tests on Windows

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#164]
# Clarification and motivation

**NB: we should probably do #165 first**

We've been building and [releasing](https://github.com/serokell/xrefcheck/releases/) windows binaries, but we haven't actually tested that they indeed work.

The readme also lists "Support for non-Unix systems" under the "For further work" section, so maybe we should invest some time into this.

The first thing to do is to setup a CI to run the haskell and bats tests on windows. GitHub Actions is probably the best way to set this up, see an example we can reuse [here](https://github.com/serokell/tztime/blob/336f585c2c7125a8ba58ffbf3dbea4f36a7c40e7/.github/workflows/ci.yml#L72-L118). The bats docs say [it supports Windows](https://bats-core.readthedocs.io/en/stable/installation.html), so this should be doable.

When this is up and running, we _may_ (hopefully not) find some bugs, in which case we'll open more follow-up issues.

A few things that _I think_ may be bugs:
* Backwards slashes in local links: `[a](b\c)`. Github and gitlab both interpret this as a link to a file named `b%5Cc`. But on a windows machine, will xrefcheck interpret this as a link to the file `c` in dir `b`?
* This line expects `rLink` to be an "absolute reference" and begin with a `/`. Appending it to `root` with `<>` works on linux, but will this behave correctly on windows? https://github.com/serokell/xrefcheck/blob/955e0ea9cf389e782cf30faf8f613756ea22cd0c/src/Xrefcheck/Verify.hs#L319

# Acceptance criteria

* We're using GitHub Actions to run the Haskell and Bats tests on Windows
* We've created issues for any bugs that come up

**Comment by Sorokin-Anton** [comment]
@dcastro I will try to run bats on my windows machine first, to see how bad things are, and then will try to learn how to add github actions. Am I right that windows machine will be hosted not on buildkite but on GitHub?

**Comment by dcastro** [comment]
> @dcastro I will try to run bats on my windows machine first, to see how bad things are, and then will try to learn how to add github actions. 

Sounds like a good plan! :+1: 

> Am I right that windows machine will be hosted not on buildkite but on GitHub?

Yes, GitHub Action's have their own [runners](https://github.com/actions/runner).

**Comment by Sorokin-Anton** [comment]
@dcastro that's what I gotv when simply run `xrefcheck` on Windows:
(builded from source with stack, launched from powershell in vscode)
```
PS C:\Users\Anton\projects\xrefcheck> xrefcheck.exe --ignored tests/**/*
Configuration file not found, using default config for GitHub repositories


xrefcheck.exe: <stderr>: hPutChar: invalid argument (Invalid argument)
```
"Funny" thing is that I can not reproduce that, and now I see question marks or some codes instead of some non-ascii symbols. 

I think maybe we should disable progress bar and output coloring (as in #185) by default on Windows using conditional compilation - this is working in vscode but not in standard porwershell or cmd, where output contains many lines like this:
```
Verifying ←[97mlocal: [←[0m←[94m←[0m←[91m←[0m←[97m■■■■■■■■■■←[0m←[97m←[0m ←[97m]←[0m←[2m←[97m?←[0m←[0m ←[93mexternal: [←Verifying ←[97mlocal: 
```
Also symbols ✓, ➥ and ⛀ (which we use for reports) are displayed as questionmarks anywhere (even in vscode terminal), but I can't suggest what to do with them. I will try to run bats after some time

**Comment by Sorokin-Anton** [comment]
I learned how to run bats inside so called Git Bash (mingw) , which looks like the only way to run them on windows, and almost all test s are failed, but for expected reasons

1: slashes in messages
```
   <   ➥  In file to-ignore\broken-link.md
   ---
   >   ➥  In file to-ignore/broken-link.md
```

2. Differently displayes error messages in network-related libraries

```
   <      ⛂  InternalException (HostCannotConnect "localhost" [Network.Socket.connect: <socket: N>: failed (Connection refused (WSAECONNREFUSED)),Network.Socket.connect: <socket: N>: failed (Connection refused (WSAECONNREFUSED))])
   ---
   <      ⛂  ConnectionFailure Network.Socket.connect: <socket: N>: failed (Connection refused (WSAECONNREFUSED))
   ---
```

(Did not tested advanced things with relative links, i.e. #165 yet)

We want that tests to pass, so I think that we should always use `/` in reports , so tests that fails like in (1) will pass.
Or we can replace `\` by `/` inside assert-diff function, bt I don't think it's a good idea.
And  we need to use some regex for network-related tests 

By the way, coloring and progress bar are displayed correctly in this shell, I think we can recommend it to xrefcheck-windows users since it comes with git. Also I think that I will need to discover how to launch it in github-actions
