### ISSUE TITLE
Rename exclusion-related config options

### ISSUE THREAD

**Issue by dcastro** [serokell/xrefcheck#171]
# Clarification and motivation

As discussed [in this thread](https://github.com/serokell/xrefcheck/issues/118#issuecomment-1242085675), the behaviours of `ignoreRefs`, `virtualFiles`, `notScanned` and `notScanned` are closely related.

* `ignoreRefs` (list of regexes)
  * Do not verify _external_ references _to_ these links.
* `virtualFiles` (glob patterns)
  * Do not verify _local_ references _to_ these files.
* `notScanned` (glob patterns)
  * Do not verify _local_ references _from_ these files.
* `ignored` (glob patterns):
  * Pretend these files don't exist.
  * References _to_ these files will fail.
  * References _from_ these files will not be verified.

To make the _intent_ of these options more obvious to the user, we could rename them to:

  * `ignoreExternalRefsTo`
  * `ignoreLocalRefsTo`
  * `ignoreRefsFrom`
  * `ignore` (note: this includes the CLI option as well)

We should also update their yaml comments in `Xrefcheck.Config.Default`.

**Note**: Please rename these one commit at a time, to make it easier to review.

# Acceptance criteria

* The 4 options have been renamed
* Their yaml comments have been updated

**Comment by Martoon-00** [comment]
I fully agree with the naming, however there seems to be a little concern on `ignoreLocalRefsTo`.

When a file contains a link to its own content, we display it as "local" (see `LocalLoc` constructor), and in this sense "local" term becomes ambiguous: whether does it mean any links to the filesystem or only links of a file to itself?

Maybe it would be nice to change `instance Buildable LocationType` so that it prints not "local", but "file-local", this should resolve the ambiguity.

**Comment by dcastro** [comment]
@Martoon-00 Agreed, I noticed the same thing too, it's been renamed it just yesterday in https://github.com/serokell/xrefcheck/issues/166 :smile:

**Comment by Martoon-00** [comment]
Oh, awesome :smile_cat:
