### ISSUE TITLE
Add --exclude option

### ISSUE THREAD

**Issue by gromakovsky** [serokell/xrefcheck#19]
# Clarification and motivation

Now that we have static binary in releases, one can use `xrefcheck` like this:
> wget -O - https://github.com/serokell/xrefcheck/releases/download/v0.1.0.0/release.tar.gz | tar xzv && xrefcheck/bin/xrefcheck

However, it will also check references in `xrefcheck/README.md` and report some errors.

Since we want to make it possible to add just one line to CI config to run `xrefcheck`, I think the easiest solution is to add `--exclude` option and pass `--exclude xrefcheck`.

Of course one can download/unpack tarball somewhere outside of current directory or supply appropriate config, but the former somewhat depends on particular CI system and the latter requires more than just one line.

# Acceptance criteria

It should be possible to pass `--exclude X` (maybe multiple times) to specify that all files in `X` (if it's a directory) or `X` itself (if it is a file) ought to be ignored.

**Comment by dcastro** [comment]
This seems to have been partially resolved in #24 (though I'm not sure what's left to do, @Martoon-00 could you fill me in please?).

In any case, it looks like the issue described here is no longer a problem, since we now publish the executables uncompressed (see [this example](https://github.com/serokell/xrefcheck/releases/tag/v0.2)).

@gromakovsky Is it ok to close this issue?

**Comment by gromakovsky** [comment]
Apparently there are 2 things we wanted to do:
1. Treat patterns with `*` like `gitignore` does.
2. Add some tests, I think I was most interested in tests for such patterns (e. g. `.git/**/*`) because the exact semantic was not clear to me and tests could clarify it.

That being said, I think it's ok to close this issue, both these items are related to the original task only to small extent. In this it would be nice to create a follow-up task.

**Comment by dcastro** [comment]
@gromakovsky Sure, I'll create follow-up tickets. 

To clarify, the patterns you're referring to are the patterns used for the `virtualFiles` config, right? 

At first I thought this was about `ignored`, but, as far as I can tell, `ignored`, `notScanned` and `ignoreRefs` don't use patterns.

**Comment by gromakovsky** [comment]
Hm, I don't remember, but I see the following item in changelog in #24:
> Make `ignored` in config consider only exact matches.

So maybe `ignored` had some support for patterns, but was changed to support only exact matches :man_shrugging: 
And then I suggested supporting gitignore-style patterns for `ignored`, but it appeared to be difficult and thus was postponed.

So for `virtualFiles` I think we just need better tests/documentation (maybe something was improved already) and for `ignored` and others we need to consider adding this feature (estimate how useful it can be).

**Comment by Martoon-00** [comment]
Previously `ignored` supported only matching on a prefix of filepaths (`doc/` also excluded `doc/a` and `doc-test`), and this was not good so I changed to exact match (`doc/` also excluded `doc/a` but not `doc-test`). Adding matching against patterns would be nice at some point.

So we have som motley set of options:
* `virtualFiles` that uses glob patterns
* `ignored` that uses exact matching
* `notScanned` that matches against a prefix

All of them probably should be changed to work with `.gitignore`-like patterns, or at least glob patterns (that turned out to be not very convenient, at least in the way how haskell libraries support it).

**Comment by dcastro** [comment]
Ok so, from what I gather, this seems like a reasonable path forward:

1. (important) Add tests for `virtualFiles` glob patterns
2. (medium priority) Change `ignored` and `notScanned` to support the same glob patterns as `virtualFiles`, for consistency.
3. (optional, desirable) Modify all options to support gitignore-style patterns.

Do you agree? Am I missing something?

**Comment by Martoon-00** [comment]
Yes, looks sensible.

**Comment by gromakovsky** [comment]
:heavy_plus_sign:

**Comment by dcastro** [comment]
Ok, created these tickets:
1. https://github.com/serokell/xrefcheck/issues/76
2. https://github.com/serokell/xrefcheck/issues/77
3. https://github.com/serokell/xrefcheck/issues/78
