### ISSUE TITLE
Warnings about files that weren't added to git yet

### ISSUE THREAD

**Issue by Sorokin-Anton** [serokell/xrefcheck#200]
# Clarification and motivation
After https://github.com/serokell/xrefcheck/pull/174, only files that were added to git exist for us. Somebody can make a new file and run xrefcheck before adding it to git (for example I add files right before commiting). List of those files can be obtained, for example, via `git ls-files --others --exclude-standard`. There is two problems for this user:
- Link in those new files are not checked
- If a link in an added to git  file references such new file, it is reported as broken

I think this should be our behavior:
- If a scannable (currently it means markdown) file is not **yet** tracked by git, we'll emit a warning saying references from that file will not be checked.
- If there is a link to such file, we'll change the message of the existing error from "file doesn't exist" to "file exists, but is not yet tracked by git" 

IMHO we can also change error to warning in second case, maybe make some CLI/config options (e.g. for simply threating such files as existent)

# Acceptance criteria
If a user runs xrefcheck before `git add`, we are not silently skipping new files, and we're not reporting links to them as links to unexisting files

**Comment by dcastro** [comment]
> IMHO we can also change error to warning in second case, maybe make some CLI/config options (e.g. for simply threating such files as existent)

We probably should not have a config option for this. This scenario should only happen locally, and the config file is meant to be committed and used by the CI.

For this same reason, I don't think it matters much if we change it from an "error" to a "warning". In practice, this means xrefcheck would terminate with the exit code 0 instead of non-0. But the exit code isn't all that useful when the program is being run by a human (which is likely to be the case when xrefcheck is run locally).
