### ISSUE TITLE
[BUG] Urls with `[` and `]` fail to parse

### ISSUE THREAD

**Issue by Martoon-00** [serokell/xrefcheck#49]
# Description

When a link contains braces, xrefcheck reports that as bad url.

# To Reproduce

Have the following link: 

This results in

```
  ➥  In file ./code/indigo/tutorial/docs/index.md
     bad reference (external) at src:66:12-120:
       - text: "new GitLab issue"
       - link: https://gitlab.com/morley-framework/morley/-/issues/new?issue[title]=Indigo%20website:%20
       - anchor: -
     ⛂  Invalid url
```

# Expected behavior

Everything passes.

# Environment

- Ubuntu
- 5ba3605ac7c5fc5da4f0474bcc04855a61265714

**Comment by Martoon-00** [comment]
Apparently the problem appeared after the recent bump of `req` package (which took place along with LTS bump). Now it accepts a URI, not a URL, and specification says

> Of the ASCII character set, the characters : / ? # [ ] @ are reserved for use as delimiters of the generic URI components and must be percent-encoded.

On the other hand, browsers take `[` and `]` just fine, and we want to stay close to their behaviour.

So the easiest way to resolve this seems to be uri-encoding the link before parsing it to URI, `uri-encode` library seems to rescue us here.

**Comment by kirelagin** [comment]
So, this problem is actually a bit tricky. I don’t want to go into all the details, but, basically, this part of RFC 3986 seems to be relevant:

>   URI producing applications should percent-encode data octets that
>   correspond to characters in the reserved set unless these characters
>   are specifically allowed by the URI scheme to represent data in that
>   component.  If a reserved character is found in a URI component and
>   no delimiting role is known for that character, then it must be
>   interpreted as representing the data octet corresponding to that
>   character's encoding in US-ASCII.

This means that an application that produces a URI with unencoded square brackets in the query component is kind of in compliance with the RFC, because it says “should”. However, since there is no delimiting role for square brackets in the query component, any application that _parses_ such a URI _MUST_ accept it.

I guess there is some room for interpretation of this paragraph, since, while the RFC gives a grammar for characters allowed within the query component, it also says

> The query component is indicated by the first question mark ("?") character and terminated by a number sign ("#") character or by the end of the URI.

which one might interpret as saying that anything that is not a `#` is not a delimiter.

To make things worse, Firefox used to escape `[` and `]` when sending them to the server, and this was actually considered [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1163028) and was changed 6 years ago. There is a nice [survey](https://bugzilla.mozilla.org/show_bug.cgi?id=1152455#c6) of the behaviours of various browsers.

All in all, given the ambiguity of the standard and what seems to be a clear actual practice, I would consider it a bug in the URI parsing library to disallow square brackets in the query component.

**Comment by kirelagin** [comment]
Ok, I opened https://github.com/mrkkrp/modern-uri/issues/39.

My current opinion:

* If we want to support the real-world, then we have to implement some hack for replacing the square brackets (and only square brackets) with their percent-encodings.
* If we want to enforce standards, then we should not allow square brackets in URLs. To provide good UX we should implement a custom error message for the case when we detect square brackets in URLs and explain that they are actually explicitly not allowed by WHATWG URL and how exactly to fix this in the user’s file.
